# Generated by Django 3.1.1 on 2020-09-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReceptionHallBook',
            fields=[
                ('RH_reserveID', models.IntegerField(primary_key=True, serialize=False)),
                ('cusId', models.CharField(max_length=10)),
                ('theme', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('timeFrom', models.TimeField()),
                ('timeTo', models.TimeField()),
            ],
            options={
                'db_table': 'ReceptionHallBooking',
            },
        ),
        migrations.CreateModel(
            name='ReceptionHallPackage',
            fields=[
                ('RH_packageID', models.IntegerField(primary_key=True, serialize=False)),
                ('theme', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=10)),
                ('description', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'ReceptionHallPackage',
            },
        ),
    ]
