# Generated by Django 3.0.8 on 2020-10-16 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='price',
            field=models.IntegerField(),
        ),
    ]
