# Generated by Django 3.0.8 on 2020-10-16 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20201016_1934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
