# Generated by Django 3.1.1 on 2020-09-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardPayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpayment',
            name='Amount',
            field=models.CharField(default=2000, max_length=100),
            preserve_default=False,
        ),
    ]
