# Generated by Django 3.1.1 on 2020-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardPayment', '0002_cardpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpayment',
            name='Amount',
            field=models.FloatField(max_length=100),
        ),
    ]
