# Generated by Django 3.1.1 on 2020-09-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('emp_index', models.AutoField(db_column='emp_Index', primary_key=True, serialize=False)),
                ('adminid', models.CharField(db_column='adminId', max_length=6)),
                ('empid', models.CharField(db_column='empId', max_length=6)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('last_login', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_index', models.AutoField(db_column='cus_Index', primary_key=True, serialize=False)),
                ('cusid', models.CharField(db_column='cusId', max_length=8)),
                ('cusnic', models.CharField(blank=True, db_column='cusNIC', max_length=10, null=True)),
                ('f_name', models.CharField(blank=True, db_column='f_Name', max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, db_column='l_Name', max_length=10, null=True)),
                ('address_l1', models.CharField(blank=True, db_column='address_L1', max_length=30, null=True)),
                ('address_l2', models.CharField(blank=True, db_column='address_L2', max_length=30, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, default='python.png', null=True, upload_to='')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('last_login', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_index', models.AutoField(db_column='emp_Index', primary_key=True, serialize=False)),
                ('empid', models.CharField(db_column='empId', max_length=6)),
                ('empnic', models.CharField(blank=True, db_column='empNIC', max_length=10, null=True)),
                ('faceid', models.CharField(blank=True, db_column='faceID', max_length=500, null=True)),
                ('f_name', models.CharField(blank=True, db_column='f_Name', max_length=10, null=True)),
                ('l_name', models.CharField(blank=True, db_column='l_Name', max_length=10, null=True)),
                ('address_l1', models.CharField(blank=True, db_column='address_L1', max_length=30, null=True)),
                ('address_l2', models.CharField(blank=True, db_column='address_L2', max_length=30, null=True)),
                ('postcode', models.IntegerField(blank=True, null=True)),
                ('img', models.CharField(blank=True, max_length=250, null=True)),
                ('basic_sal', models.FloatField(blank=True, db_column='basic_Sal', null=True)),
                ('ot_rate', models.FloatField(blank=True, db_column='OT_Rate', null=True)),
                ('reg_date', models.DateField(blank=True, db_column='reg_Date', null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=150, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('remark', models.CharField(blank=True, max_length=500, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=6, null=True)),
                ('last_login', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'employee',
                'managed': True,
            },
        ),
    ]
