# Generated by Django 3.1.1 on 2020-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': True},
        ),
    ]
