# Generated by Django 3.1.1 on 2020-09-18 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0002_auto_20200918_2310'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
    ]
