# Generated by Django 3.1.1 on 2020-09-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0005_auto_20200918_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='occu',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
