# Generated by Django 3.1.1 on 2020-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userlogin', '0006_employee_occu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='img',
            field=models.ImageField(blank=True, default='python.png', null=True, upload_to=''),
        ),
    ]
