# Generated by Django 3.1.1 on 2020-10-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bpacname', models.CharField(max_length=100, null=True)),
                ('bfname', models.CharField(max_length=100)),
                ('blname', models.CharField(max_length=100)),
                ('bdate', models.DateField()),
                ('badults', models.CharField(max_length=20)),
                ('bchild', models.CharField(max_length=20)),
                ('bemail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offertitle', models.CharField(max_length=100, null=True)),
                ('offerprice', models.CharField(max_length=100, null=True)),
                ('offerdis', models.CharField(max_length=100, null=True)),
                ('offerdes', models.CharField(max_length=1000, null=True)),
                ('condition', models.CharField(max_length=1000, null=True)),
                ('ofimage', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'offers',
            },
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptitle', models.CharField(max_length=100)),
                ('ptype', models.CharField(max_length=100)),
                ('pprice', models.CharField(max_length=100)),
                ('pdays', models.CharField(max_length=20)),
                ('pdes', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'packages',
            },
        ),
    ]
