# Generated by Django 3.1.1 on 2020-10-17 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpackages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offers',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offerdes',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='offertitle',
        ),
        migrations.RemoveField(
            model_name='offers',
            name='ofimage',
        ),
    ]
