# Generated by Django 3.1.1 on 2020-10-17 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpackages', '0002_auto_20201017_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='offerdis',
            new_name='ptitle',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='offerprice',
            new_name='ptype',
        ),
    ]
