# Generated by Django 3.1.1 on 2020-10-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpackages', '0003_auto_20201017_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='ptitle',
            new_name='offerdis',
        ),
        migrations.RenameField(
            model_name='offers',
            old_name='ptype',
            new_name='offerprice',
        ),
    ]
