# Generated by Django 3.1.1 on 2020-10-17 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpackages', '0004_auto_20201017_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='condition',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='offerdes',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='offertitle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='offers',
            name='ofimage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offerdis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='offerprice',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
