# Generated by Django 3.1.1 on 2020-10-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revokedPayment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revokedpayment',
            name='Paid_amount',
            field=models.FloatField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
