# Generated by Django 3.1.1 on 2020-10-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('revokedPayment', '0002_revokedpayment_paid_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RevokedPayment',
            new_name='revokedPayments',
        ),
    ]
