# Generated by Django 3.1.1 on 2020-10-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revokedPayment', '0003_auto_20201016_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='revokedpayments',
            name='Payment_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
