# Generated by Django 3.1.1 on 2020-09-07 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cashPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_type', models.CharField(max_length=100)),
                ('Item_number', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('Net_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
