# Generated by Django 3.0.8 on 2020-09-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoTitle', models.CharField(max_length=30)),
                ('promoDescription', models.CharField(max_length=80)),
                ('promoImage', models.ImageField(upload_to='promotions/images/')),
                ('promoPrice', models.CharField(max_length=15)),
                ('expiredate', models.DateTimeField(null=True)),
            ],
        ),
    ]
