# Generated by Django 3.1.1 on 2020-09-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashPayment', '0002_cashpayment_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashpayment',
            name='Net_amount',
            field=models.FloatField(max_length=100),
        ),
    ]
